name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: "30 11 1 * *" # At 11:30 on start of the month
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://coderwhodreams.hashnode.dev/rss.xml"
